from app import app
from app import helper
from test_helper import assertObejct
from flask import json
from testData import rawTimetableData
import xml.etree.ElementTree as xml
import subprocess
from xmljson import badgerfish as bf


"""
test hello world API
"""
def test_helloAPI():
    response = app.test_client().get('/')

    assert response.status_code == 200
    assert response.data == b'hello'

"""
test generate timetables API
"""
def test_generateTimetablesAPI():
    response = app.test_client().post(
        '/api/v1/test',
        data=json.dumps(rawTimetableData),
        content_type='application/json',
    )

    # check anything goes wrong during the transfromation from json to xml
    assert response.status_code == 200

def expectedResultStudent():
    return [{'name': '2019 Automatic Group Automatic Subgroup', 'days': [{'hours': [{'subject': 'physics', 'name': 8, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'A101'}]}, {'subject': 'physics', 'name': 9, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'A101'}]}, {'name': 10, 'empty': 'true'}, {'name': 11, 'empty': 'true'}, {'subject': 'maths', 'name': 12, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'B101'}]}, {'name': 13, 'empty': 'true'}], 'name': 'Monday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'subject': 'maths', 'name': 10, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'B101'}]}, {'name': 11, 'empty': 'true'}, {'name': 12, 'empty': 'true'}, {'name': 13, 'empty': 'true'}], 'name': 'Tuesday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'subject': 'chemistry', 'name': 11, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher1'}], 'room': [{'name': 'B101'}]}, {'name': 12, 'empty': 'true'}, {'subject': 'chemistry', 'name': 13, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher1'}], 'room': [{'name': 'B101'}]}], 'name': 'Wednesday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'name': 11, 'empty': 'true'}, {'name': 12, 'empty': 'true'}, {'name': 13, 'empty': 'true'}], 'name': 'Thursday'}]}, {'name': '2020 Automatic Group Automatic Subgroup', 'days': [{'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'name': 11, 'empty': 'true'}, {'name': 12, 'empty': 'true'}, {'subject': 'maths', 'name': 13, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'B101'}]}], 'name': 'Monday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'subject': 'chemistry', 'name': 11, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher1'}], 'room': [{'name': 'B101'}]}, {'name': 12, 'empty': 'true'}, {'subject': 'physics', 'name': 13, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'A101'}]}], 'name': 'Tuesday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'subject': 'physics', 'name': 11, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher2'}], 'room': [{'name': 'A101'}]}, {'name': 12, 'empty': 'true'}, {'name': 13, 'empty': 'true'}], 'name': 'Wednesday'}, {'hours': [{'name': 8, 'empty': 'true'}, {'name': 9, 'empty': 'true'}, {'name': 10, 'empty': 'true'}, {'name': 11, 'empty': 'true'}, {'subject': 'chemistry', 'name': 12, 'activity_tag': [{'name': 'tag1'}], 'teachers': [{'name': 'teacher1'}], 'room': [{'name': 'B101'}]}, {'name': 13, 'empty': 'true'}], 'name': 'Thursday'}]}]

"""
use fet to test whether the generated xml file is valid or not
and validate some values in the timetable data files generated by fet
"""
def test_fet():
    stdoutdata = subprocess.getoutput("sudo fet-cl --inputfile=test.fet")
    # wheter fet generator goes well
    assert stdoutdata.splitlines()[-1] == "Simulation successful"

    prefix = "./timetables/test/test_"
    with open(prefix + "subgroups.xml", "r") as fh:
        tmp = bf.data(xml.fromstring(fh.read()))
        testResultStudent = helper.beautifyDays(tmp["Students_Timetable"]["Subgroup"], "teachers", "Teacher")
        # validate some values in the timetable data files generated by fet
        assert testResultStudent[0]['name'] == "2019 Automatic Group Automatic Subgroup"
        assert testResultStudent[0]['days'][0]['hours'][0]['name'] == 8
        print(testResultStudent[0]['days'][0]['hours'][0])
        # assert testResultStudent[0]['days'][0]['hours'][0]['subject'] == "physics"

    stdoutdata = subprocess.getoutput("sudo rm -rf ./timetables/test")
